version: "3.7"
services:
  database:
    image: postgres
    container_name: settings_db
    restart: always
    env_file:
      - .env
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - data:/var/lib/postgresql/data
    command: -p ${DB_PORT}

  server:
    container_name: settings_ms
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - vsftpd
      - database
    links:
      - vsftpd
      - database
    networks:
      - default
      - linking_mq_net
    external_links:
      - rabbitmq
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - POSTGRES_HOST=database

  vsftpd:
    container_name: vsftpd
    image: fauria/vsftpd
    restart: always
    env_file:
      - .env
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    expose:
      - 21
    environment:
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    volumes:
      - ./var/app/ftp:/home/vsftpd
      - ./var/log/ftp:/var/log/vsftpd


volumes:
  data:

networks:
  linking_mq_net:
    external: true