version: "3.7"
services:
  database:
    image: postgres
    container_name: settings_db
    restart: always
    env_file:
      - .env
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    command: -p 5433

  server:
    container_name: settings_ms
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    links:
      - database
    networks:
      - default
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:${DB_PORT}/${POSTGRES_DB}
volumes:
  data: